---
driver:
  name: vagrant
  require_chef_omnibus: 11.10.0
  customize:
    memory: 1024
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-7.4
  run_list:
  - recipe[apt]

suites:
- name: mongod-recipe
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_recipe]
- name: mongod-recipe-auth
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_recipe_auth]
- name: mongod-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_lwrp]
- name: replicaset-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::replica_set_lwrp]
- name: replicaset-lwrp-auth
  run_list:
    - recipe[hipsnip-mongodb_test::replica_set_lwrp_auth]